"""create suppliers and admission cases

Revision ID: 753aba797976
Revises: 695904b52a89
Create Date: 2026-08-31 19:28:32.740474

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "753aba797976"
down_revision: str | Sequence[str] | None = "695904b52a89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("declared_registration_id", sa.String(length=100), nullable=False),
        sa.Column("category_code", sa.String(length=64), nullable=False),
        sa.Column(
            "eligibility_status",
            sa.Enum(
                "candidate",
                "approved",
                "suspended",
                "expired",
                "rejected",
                name="supplier_eligibility_status",
                native_enum=False,
            ),
            server_default="candidate",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "eligibility_status IN ('candidate', 'approved', 'suspended', 'expired', 'rejected')",
            name="supplier_eligibility_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("declared_registration_id"),
    )
    op.create_table(
        "admission_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_documents",
                "analyzing",
                "evidence_reviewing",
                "pending_approval",
                "approved",
                "rejected",
                "archived",
                name="admission_case_status",
                native_enum=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "status IN ('draft', 'pending_documents', 'analyzing', "
                "'evidence_reviewing', 'pending_approval', 'approved', "
                "'rejected', 'archived')"
            ),
            name="admission_case_status",
        ),
        sa.ForeignKeyConstraint(["submitted_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admission_cases_submitted_by_user_id"),
        "admission_cases",
        ["submitted_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admission_cases_supplier_id"), "admission_cases", ["supplier_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admission_cases_supplier_id"), table_name="admission_cases")
    op.drop_index(op.f("ix_admission_cases_submitted_by_user_id"), table_name="admission_cases")
    op.drop_table("admission_cases")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
