"""create documents table

Revision ID: 8059d69192f3
Revises: 753aba797976
Create Date: 2026-08-31 20:12:57.851108

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8059d69192f3"
down_revision: str | Sequence[str] | None = "753aba797976"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admission_case_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "business_license",
                "quality_certificate",
                "quotation",
                "delivery_history",
                name="document_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("original_file_name", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "document_type IN ('business_license', 'quality_certificate', "
                "'quotation', 'delivery_history')"
            ),
            name="document_type",
        ),
        sa.CheckConstraint("char_length(sha256) = 64", name="document_sha256_length"),
        sa.CheckConstraint("file_size_bytes > 0", name="document_file_size_positive"),
        sa.ForeignKeyConstraint(["admission_case_id"], ["admission_cases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["uploaded_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("admission_case_id", "sha256", name="uq_documents_case_sha256"),
    )
    op.create_index(
        op.f("ix_documents_admission_case_id"), "documents", ["admission_case_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_admission_case_id"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
