"""create rag corpus persistence tables

Revision ID: b0604f36e9a4
Revises: 8acab623700e
Create Date: 2026-09-08 12:05:49.369406

"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0604f36e9a4"
down_revision: str | Sequence[str] | None = "8acab623700e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rag_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=False),
        sa.Column(
            "source_origin",
            sa.Enum(
                "synthetic",
                "gov_document",
                "commercial",
                name="rag_source_origin",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("canonical_url", sa.String(length=500), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source_origin = 'synthetic' AND canonical_url IS NULL AND retrieved_at IS NULL) "
            "OR (source_origin <> 'synthetic' AND canonical_url IS NOT NULL "
            "AND retrieved_at IS NOT NULL)",
            name="rag_source_provenance",
        ),
        sa.CheckConstraint(
            "source_origin IN ('synthetic', 'gov_document', 'commercial')", name="rag_source_origin"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_table(
        "rag_editions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("edition_key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("published_on", sa.Date(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_until", sa.Date(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "direct_policy",
                "background",
                "conditional_reference",
                "version_negative",
                "background_and_version_negative",
                name="rag_edition_role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("applicability", sa.String(length=500), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("normalized_sha256", sa.String(length=64), nullable=False),
        sa.Column("processor_version", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('direct_policy', 'background', 'conditional_reference', "
            "'version_negative', 'background_and_version_negative')",
            name="rag_edition_role",
        ),
        sa.CheckConstraint(
            "char_length(normalized_sha256) = 64", name="rag_edition_normalized_sha_length"
        ),
        sa.CheckConstraint(
            "char_length(snapshot_sha256) = 64", name="rag_edition_snapshot_sha_length"
        ),
        sa.CheckConstraint(
            "effective_until IS NULL OR effective_until >= effective_from",
            name="rag_edition_effective_range",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["rag_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("edition_key", name="uq_rag_editions_edition_key"),
    )
    op.create_index(op.f("ix_rag_editions_source_id"), "rag_editions", ["source_id"], unique=False)
    op.create_table(
        "rag_edition_supersedes",
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("predecessor_edition_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("edition_id <> predecessor_edition_id", name="rag_supersedes_not_self"),
        sa.ForeignKeyConstraint(["edition_id"], ["rag_editions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["predecessor_edition_id"], ["rag_editions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("edition_id", "predecessor_edition_id"),
    )
    op.create_index(
        op.f("ix_rag_edition_supersedes_predecessor_edition_id"),
        "rag_edition_supersedes",
        ["predecessor_edition_id"],
        unique=False,
    )
    op.create_table(
        "rag_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("parent_node_id", sa.Uuid(), nullable=True),
        sa.Column("node_key", sa.String(length=200), nullable=False),
        sa.Column(
            "node_type",
            sa.Enum(
                "document",
                "chapter",
                "section",
                "article",
                "paragraph",
                "item",
                "table",
                "table_row",
                name="rag_node_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("locator", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_sha256", sa.String(length=64), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("normalized_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "array_length(locator, 1) >= 1 AND array_position(locator, '') IS NULL",
            name="rag_node_locator_nonempty",
        ),
        sa.CheckConstraint(
            "node_type IN ('document', 'chapter', 'section', 'article', 'paragraph', "
            "'item', 'table', 'table_row')",
            name="rag_node_type",
        ),
        sa.CheckConstraint("char_length(body_sha256) = 64", name="rag_node_body_sha_length"),
        sa.CheckConstraint("char_length(normalized_sha256) = 64", name="sha_normalized_length"),
        sa.CheckConstraint("char_length(snapshot_sha256) = 64", name="sha_snapshot_length"),
        sa.CheckConstraint("char_start >= 0 AND char_end > char_start", name="rag_node_char_range"),
        sa.CheckConstraint(
            "length(body) = char_end - char_start", name="rag_node_body_matches_span"
        ),
        sa.ForeignKeyConstraint(["edition_id"], ["rag_editions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_node_id"], ["rag_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("edition_id", "locator", name="uq_rag_nodes_edition_locator"),
        sa.UniqueConstraint("node_key", name="uq_rag_nodes_node_key"),
    )
    op.create_index(op.f("ix_rag_nodes_edition_id"), "rag_nodes", ["edition_id"], unique=False)
    op.create_index(
        op.f("ix_rag_nodes_parent_node_id"), "rag_nodes", ["parent_node_id"], unique=False
    )
    op.create_table(
        "rag_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_key", sa.String(length=200), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("display_text", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("node_body_sha256", sa.String(length=64), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("normalized_sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("embedding_dim", sa.Integer(), nullable=True),
        sa.Column("embedded_text_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(embedding IS NULL AND embedding_model IS NULL AND embedding_dim IS NULL "
            "AND embedded_text_sha256 IS NULL) OR "
            "(embedding IS NOT NULL AND embedding_model IS NOT NULL AND embedding_dim IS NOT NULL "
            "AND embedded_text_sha256 IS NOT NULL)",
            name="rag_chunk_embedding_all_or_none",
        ),
        sa.CheckConstraint(
            "char_length(node_body_sha256) = 64", name="rag_chunk_node_body_sha_length"
        ),
        sa.CheckConstraint("char_length(normalized_sha256) = 64", name="sha_normalized_length"),
        sa.CheckConstraint("char_length(snapshot_sha256) = 64", name="sha_snapshot_length"),
        sa.CheckConstraint(
            "char_start >= 0 AND char_end > char_start", name="rag_chunk_char_range"
        ),
        sa.CheckConstraint(
            "embedding_dim IS NULL OR embedding_dim = 1024", name="rag_chunk_embedding_dim_pinned"
        ),
        sa.CheckConstraint(
            "length(display_text) = char_end - char_start", name="rag_chunk_display_matches_span"
        ),
        sa.CheckConstraint(
            "strpos(search_text, display_text) > 0", name="rag_chunk_search_contains_display"
        ),
        sa.ForeignKeyConstraint(["edition_id"], ["rag_editions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["node_id"], ["rag_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_key", name="uq_rag_chunks_chunk_key"),
    )
    op.create_index(op.f("ix_rag_chunks_edition_id"), "rag_chunks", ["edition_id"], unique=False)
    op.create_index(op.f("ix_rag_chunks_node_id"), "rag_chunks", ["node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rag_chunks_node_id"), table_name="rag_chunks")
    op.drop_index(op.f("ix_rag_chunks_edition_id"), table_name="rag_chunks")
    op.drop_table("rag_chunks")
    op.drop_index(op.f("ix_rag_nodes_parent_node_id"), table_name="rag_nodes")
    op.drop_index(op.f("ix_rag_nodes_edition_id"), table_name="rag_nodes")
    op.drop_table("rag_nodes")
    op.drop_index(
        op.f("ix_rag_edition_supersedes_predecessor_edition_id"),
        table_name="rag_edition_supersedes",
    )
    op.drop_table("rag_edition_supersedes")
    op.drop_index(op.f("ix_rag_editions_source_id"), table_name="rag_editions")
    op.drop_table("rag_editions")
    op.drop_table("rag_sources")
    # ### end Alembic commands ###
