"""create audit events table

Revision ID: e070d366b661
Revises: 8059d69192f3
Create Date: 2026-08-31 21:04:46.962553

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e070d366b661"
down_revision: str | Sequence[str] | None = "8059d69192f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum("admission_case", name="audit_subject_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "admission_case_created",
                "documents_registered",
                name="audit_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('admission_case_created', 'documents_registered')",
            name="audit_event_type",
        ),
        sa.CheckConstraint("subject_type IN ('admission_case')", name="audit_subject_type"),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_subject",
        "audit_events",
        ["subject_type", "subject_id", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_events_subject", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
